#!/usr/bin/env python3

import argparse
import json

from jsonmerge import merge

def create_parser():
    parser = argparse.ArgumentParser(
        prog="jsonmerge", description='Merge JSON files')
    parser.add_argument("output", help="Where to output")
    parser.add_argument("files", nargs="+", help="Where to output")
    return parser.parse_args()

if __name__ == '__main__':
    _args = create_parser()
    _res = { "data": []}
    schema = {"data": { 'mergeStrategy': 'append'} }
    for f in _args.files:
        try:
            with open(f) as i:
                _res = merge(_res, json.load(i), schema)
        except:
            pass
    _res["data"] = [dict(s) for s in set(frozenset(d.items()) for d in _res["data"])]
    with open(_args.output, "w") as o:
        json.dump(_res, o)