#!/usr/bin/env python3

import argparse
import json
import os

def create_parser():
    parser = argparse.ArgumentParser(
        prog="jsonmerge", description='Merge JSON files')
    parser.add_argument("output", help="Where to output")
    parser.add_argument("files", nargs="+", help="What's the input")
    return parser.parse_args()

if __name__ == '__main__':
    _args = create_parser()
    _res = { "data": []}
    for f in _args.files:
        try:
            if os.path.basename(f) != os.path.basename(_args.output):
                print("Reading {}".format(f))
                with open(f) as i:
                    _res["data"] += json.load(i)["data"]
        except Exception as e:
            print("Exception: {}".format(e))
    _res["data"] = [dict(s) for s in set(frozenset(d.items()) for d in _res["data"])]
    print("Found overall {} items".format(len(_res["data"])))
    with open(_args.output, "w") as o:
        json.dump(_res, o, sort_keys=True)